### PR TITLE
Swapped "expected" and "actual" display order in fail message for assert_same

### PR DESCRIPTION
**Pull request by khalilfazal**
Also changed voice to past tense

### CODE REVIEW

**Comment by kou** [comment]
Why do we need to swap? Other assertions such as `assert_equal` use `expected` then `actual` order.

**Comment by khalilfazal** [comment]
I don't intend to change how assert_* methods are called.
The issue is only in how the fail messages are displayed.

The irregularity is in how the fail message is currently displayed for `assert_same` where
the order of `expected` and `actual` is reversed.

An alternate solution would make the fail message for `assert_same` display `expected` before `actual` and in doing so match how `assert_equal` displays its fail message.

**Comment by kou** [comment]
I'm sorry but I didn't understand what you say yet.

It seems that the current fail message for `assert_same` uses `expected` -> `actual` order. Is it not right?

**Comment by khalilfazal** [comment]
> It seems that the current fail message for `assert_same` uses `expected` -> `actual` order. Is it not right?

The current fail message template for `assert_same` is this:

    <"thing">
    with id <#{thing.__id__}> expected to be equal? to
    <"thing">
    with id <#{thing2.__id__}>.

It's written with ambiguous English grammar. Shouldn't there be a verb between `<#{thing.__id__}>` and "expected"? Well if a verb were placed there like "was", then it would be more clear that the message is not in `expected` -> `actual` order.

**Comment by kou** [comment]
Thanks.
I understand.

I've fixed assertion messages.

**Pull request closed without merging**
