### PR TITLE
thread runner: add missing test result support

### PR DESCRIPTION
**Pull request by tikkss**
GitHub: fix GH-271

Reported by Takahiro Ueda. Thanks!!!

### CODE REVIEW

**Comment by tikkss** [comment]
### Reproduce code(`test/test-sample.rb`)

```ruby
require 'test-unit'

class SampleTest < Test::Unit::TestCase
  def test_pend
    pend("pend")
  end

  def test_notify
    notify("I'm here!")
  end
end
```

### Steps to reproduce

```console
$ ruby test/run-test.rb -t SampleTest --parallel=thread
```

### Before changes

```console
$ ruby test/run-test.rb -t SampleTest --parallel=thread
Loaded suite test
Started
E
================================================================================================================================================================
Error: test_notify(SampleTest): NoMethodError: undefined method `add_notification' for an instance of Test::Unit::SubTestResult
E
================================================================================================================================================================
Error: test_pend(SampleTest): NoMethodError: undefined method `add_pending' for an instance of Test::Unit::SubTestResult
<internal:kernel>:187:in `loop'
Cause0: Test::Unit::PendedError: pend
/Users/zzz/src/github.com/test-unit/test-unit/test/test-sample.rb:5:in `test_pend'
     2:
     3: class SampleTest < Test::Unit::TestCase
     4:   def test_pend
  => 5:     pend("pend")
     6:   end
     7:
     8:   def test_notify
<internal:kernel>:187:in `loop'
================================================================================================================================================================
/Users/zzz/src/github.com/test-unit/test-unit/test/test-sample.rb:9:in `test_notify'
      6:   end
      7:
      8:   def test_notify
  =>  9:     notify("I'm here!")
     10:   end
     11: end
     12:
<internal:kernel>:187:in `loop'
================================================================================================================================================================
Finished in 0.008755 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------
2 tests, 0 assertions, 0 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------
228.44 tests/s, 0.00 assertions/s
```

### After changes

```console
$ ruby test/run-test.rb -t SampleTest --parallel=thread
Loaded suite test
Started
N
================================================================================================================================================================
Notification: I'm here! [test_notify(SampleTest)]
/Users/zzz/src/github.com/test-unit/test-unit/test/test-sample.rb:9:in `test_notify'
================================================================================================================================================================
P
================================================================================================================================================================
Pending: test_pend(SampleTest): pend
/Users/zzz/src/github.com/test-unit/test-unit/test/test-sample.rb:5:in `test_pend'
     2:
     3: class SampleTest < Test::Unit::TestCase
     4:   def test_pend
  => 5:     pend("pend")
     6:   end
     7:
     8:   def test_notify
<internal:kernel>:187:in `loop'
================================================================================================================================================================
Finished in 0.005751 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------
2 tests, 0 assertions, 0 failures, 0 errors, 1 pendings, 0 omissions, 1 notifications
50% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------
347.77 tests/s, 0.00 assertions/s
```

**Comment by kou** [comment]
Can we add tests for them?

**Comment by tikkss** [comment]
OK, I'll check it out!

**Comment by tikkss** [comment]
I'll add tests for them by following these steps.

* Improve `test-test-result.rb` on GH-273
* Add a new test file, `test-sub-test-result.rb` based on `test-test-result.rb` on this PR.

**Comment by kou** [comment]
Hmm. We don't want to maintain test result level tests...
Can we add test case level tests not test result level tests?
Something like the following:

```diff
index aa322de..e3c7fc4 100644
--- a/test/test-pending.rb
+++ b/test/test-pending.rb
@@ -32,6 +32,10 @@ class TestUnitPending < Test::Unit::TestCase
     end
   end
 
+  def test_pend_always
+    pend("Always pending")
+  end
+
   def test_pend
     test = nil
     result = _run_test("test_pend") {|t| test = t}
```

**Comment by tikkss** [comment]
I understood that we should add test case level tests not test result level tests. Thanks!
However, when I apply the suggested code to the master branch (ad352e1), it always pass not 100%:

Is this intentional?

```console
$ ruby test/run-test.rb
Loaded suite test
Started
O
================================================================================================================================================================
Omission: memory usage collection isn't supported on this platform [test_fail(Test::Unit::TestAssertNothingLeakedMemory)]
/Users/zzz/src/github.com/test-unit/test-unit/test/test-assertions.rb:2986:in `block in test_fail'
================================================================================================================================================================
O
================================================================================================================================================================
Omission: memory usage collection isn't supported on this platform [test_pass(Test::Unit::TestAssertNothingLeakedMemory)]
/Users/zzz/src/github.com/test-unit/test-unit/test/test-assertions.rb:2933:in `block in test_pass'
================================================================================================================================================================
O
================================================================================================================================================================
Omission: memory usage collection isn't supported on this platform [test_pass_message(Test::Unit::TestAssertNothingLeakedMemory)]
/Users/zzz/src/github.com/test-unit/test-unit/test/test-assertions.rb:2944:in `block in test_pass_message'
================================================================================================================================================================
O
================================================================================================================================================================
Omission: memory usage collection isn't supported on this platform [test_pass_target(Test::Unit::TestAssertNothingLeakedMemory)]
/Users/zzz/src/github.com/test-unit/test-unit/test/test-assertions.rb:2957:in `block in test_pass_target'
================================================================================================================================================================
O
================================================================================================================================================================
Omission: test for JRuby [test_assert_raise_jruby(Test::Unit::TestAssertions)]
/Users/zzz/src/github.com/test-unit/test-unit/test/testunit-test-util.rb:15:in `jruby_only_test'
================================================================================================================================================================
O
================================================================================================================================================================
Omission: test for JRuby [test_error_inside_jruby(TestCodeSnippet::TestJRuby)]
/Users/zzz/src/github.com/test-unit/test-unit/test/testunit-test-util.rb:15:in `jruby_only_test'
================================================================================================================================================================
P
================================================================================================================================================================
Pending: test_pend_always(TestUnitPending): Always pending
/Users/zzz/src/github.com/test-unit/test-unit/test/test-pending.rb:36:in `test_pend_always'
     33:   end
     34:
     35:   def test_pend_always
  => 36:     pend("Always pending")
     37:   end
     38:
     39:   def test_pend
================================================================================================================================================================
Finished in 0.665884 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------
475 tests, 1612 assertions, 0 failures, 0 errors, 1 pendings, 6 omissions, 0 notifications
99.7868% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------
713.34 tests/s, 2420.84 assertions/s
```

**Comment by kou** [comment]
Ah, hmm... It's not expected...

The current parallel implementation can't use `run_all_tests`/`run_tests` at the same time. Let's reconsider this limitation for easy to test.

**Comment by tikkss** [comment]
Thanks for your reply. I didn't understand the limitation, but we would like to reconsider it for easy to test.

**Comment by kou** [comment]
I merge this without tests for these case.
I want to release a new version for upcoming Ruby 3.4.0.

**Comment by tikkss** [comment]
OK. I would like to open a separate PR for easy to test. Thanks!

**Pull request merged**
