### PR TITLE
Do not contain needless `test_files` in gem package

### PR DESCRIPTION
**Pull request by kachick**
In my understanding, including `test_files` in gemspec is needless now

* https://github.com/rubygems/guides/issues/90
* https://github.com/rubygems/bundler/pull/3207
* https://pocke.hatenablog.com/entry/2020/10/24/171955 (ja)

I personally use below rake task in own gems to check the packing results.

```ruby
desc 'Prevent miss packaging!'
task :view_packaging_files do
  sh 'rm -rf ./pkg'
  sh 'rake build'
  cd 'pkg' do
    sh 'gem unpack *.gem'
    sh 'tree -I *\.gem'
  end
  sh 'rm -rf ./pkg'
end
```

Before this change
---

```plaintext
.
└── test-unit-3.4.5
    ├── BSDL
    ├── COPYING
    ├── PSFL
    ├── README.md
    ├── Rakefile
    ├── doc
    │   └── text
    │       ├── getting-started.md
    │       ├── how-to.md
    │       └── news.md
    ├── lib
    │   ├── test
    │   │   ├── unit
    │   │   │   ├── assertion-failed-error.rb
    │   │   │   ├── assertions.rb
    │   │   │   ├── attribute-matcher.rb
    │   │   │   ├── attribute.rb
    │   │   │   ├── auto-runner-loader.rb
    │   │   │   ├── autorunner.rb
    │   │   │   ├── code-snippet-fetcher.rb
    │   │   │   ├── collector
    │   │   │   │   ├── descendant.rb
    │   │   │   │   ├── dir.rb
    │   │   │   │   ├── load.rb
    │   │   │   │   ├── objectspace.rb
    │   │   │   │   └── xml.rb
    │   │   │   ├── collector.rb
    │   │   │   ├── color-scheme.rb
    │   │   │   ├── color.rb
    │   │   │   ├── data-sets.rb
    │   │   │   ├── data.rb
    │   │   │   ├── diff.rb
    │   │   │   ├── error.rb
    │   │   │   ├── exception-handler.rb
    │   │   │   ├── failure.rb
    │   │   │   ├── fault-location-detector.rb
    │   │   │   ├── fixture.rb
    │   │   │   ├── notification.rb
    │   │   │   ├── omission.rb
    │   │   │   ├── pending.rb
    │   │   │   ├── priority.rb
    │   │   │   ├── runner
    │   │   │   │   ├── console.rb
    │   │   │   │   ├── emacs.rb
    │   │   │   │   └── xml.rb
    │   │   │   ├── test-suite-creator.rb
    │   │   │   ├── testcase.rb
    │   │   │   ├── testresult.rb
    │   │   │   ├── testsuite.rb
    │   │   │   ├── ui
    │   │   │   │   ├── console
    │   │   │   │   │   ├── outputlevel.rb
    │   │   │   │   │   └── testrunner.rb
    │   │   │   │   ├── emacs
    │   │   │   │   │   └── testrunner.rb
    │   │   │   │   ├── testrunner.rb
    │   │   │   │   ├── testrunnermediator.rb
    │   │   │   │   ├── testrunnerutilities.rb
    │   │   │   │   └── xml
    │   │   │   │       └── testrunner.rb
    │   │   │   ├── util
    │   │   │   │   ├── backtracefilter.rb
    │   │   │   │   ├── method-owner-finder.rb
    │   │   │   │   ├── observable.rb
    │   │   │   │   ├── output.rb
    │   │   │   │   └── procwrapper.rb
    │   │   │   ├── version.rb
    │   │   │   └── warning.rb
    │   │   └── unit.rb
    │   └── test-unit.rb
    ├── sample
    │   ├── adder.rb
    │   ├── subtracter.rb
    │   ├── test_adder.rb
    │   ├── test_subtracter.rb
    │   └── test_user.rb
    └── test
        ├── collector
        │   ├── test-descendant.rb
        │   ├── test-load.rb
        │   ├── test_dir.rb
        │   └── test_objectspace.rb
        ├── fixtures
        │   ├── header-label.csv
        │   ├── header-label.tsv
        │   ├── header.csv
        │   ├── header.tsv
        │   ├── no-header.csv
        │   ├── no-header.tsv
        │   └── plus.csv
        ├── run-test.rb
        ├── test-assertions.rb
        ├── test-attribute-matcher.rb
        ├── test-attribute.rb
        ├── test-code-snippet.rb
        ├── test-color-scheme.rb
        ├── test-color.rb
        ├── test-data.rb
        ├── test-diff.rb
        ├── test-emacs-runner.rb
        ├── test-error.rb
        ├── test-failure.rb
        ├── test-fault-location-detector.rb
        ├── test-fixture.rb
        ├── test-notification.rb
        ├── test-omission.rb
        ├── test-pending.rb
        ├── test-priority.rb
        ├── test-test-case.rb
        ├── test-test-result.rb
        ├── test-test-suite-creator.rb
        ├── test-test-suite.rb
        ├── testunit-test-util.rb
        ├── ui
        │   └── test_testrunmediator.rb
        └── util
            ├── test-method-owner-finder.rb
            ├── test-output.rb
            ├── test_backtracefilter.rb
            ├── test_observable.rb
            └── test_procwrapper.rb

19 directories, 103 files
```

After this change
---

```plaintext.
.
└── test-unit-3.4.5
    ├── BSDL
    ├── COPYING
    ├── PSFL
    ├── README.md
    ├── Rakefile
    ├── doc
    │   └── text
    │       ├── getting-started.md
    │       ├── how-to.md
    │       └── news.md
    ├── lib
    │   ├── test
    │   │   ├── unit
    │   │   │   ├── assertion-failed-error.rb
    │   │   │   ├── assertions.rb
    │   │   │   ├── attribute-matcher.rb
    │   │   │   ├── attribute.rb
    │   │   │   ├── auto-runner-loader.rb
    │   │   │   ├── autorunner.rb
    │   │   │   ├── code-snippet-fetcher.rb
    │   │   │   ├── collector
    │   │   │   │   ├── descendant.rb
    │   │   │   │   ├── dir.rb
    │   │   │   │   ├── load.rb
    │   │   │   │   ├── objectspace.rb
    │   │   │   │   └── xml.rb
    │   │   │   ├── collector.rb
    │   │   │   ├── color-scheme.rb
    │   │   │   ├── color.rb
    │   │   │   ├── data-sets.rb
    │   │   │   ├── data.rb
    │   │   │   ├── diff.rb
    │   │   │   ├── error.rb
    │   │   │   ├── exception-handler.rb
    │   │   │   ├── failure.rb
    │   │   │   ├── fault-location-detector.rb
    │   │   │   ├── fixture.rb
    │   │   │   ├── notification.rb
    │   │   │   ├── omission.rb
    │   │   │   ├── pending.rb
    │   │   │   ├── priority.rb
    │   │   │   ├── runner
    │   │   │   │   ├── console.rb
    │   │   │   │   ├── emacs.rb
    │   │   │   │   └── xml.rb
    │   │   │   ├── test-suite-creator.rb
    │   │   │   ├── testcase.rb
    │   │   │   ├── testresult.rb
    │   │   │   ├── testsuite.rb
    │   │   │   ├── ui
    │   │   │   │   ├── console
    │   │   │   │   │   ├── outputlevel.rb
    │   │   │   │   │   └── testrunner.rb
    │   │   │   │   ├── emacs
    │   │   │   │   │   └── testrunner.rb
    │   │   │   │   ├── testrunner.rb
    │   │   │   │   ├── testrunnermediator.rb
    │   │   │   │   ├── testrunnerutilities.rb
    │   │   │   │   └── xml
    │   │   │   │       └── testrunner.rb
    │   │   │   ├── util
    │   │   │   │   ├── backtracefilter.rb
    │   │   │   │   ├── method-owner-finder.rb
    │   │   │   │   ├── observable.rb
    │   │   │   │   ├── output.rb
    │   │   │   │   └── procwrapper.rb
    │   │   │   ├── version.rb
    │   │   │   └── warning.rb
    │   │   └── unit.rb
    │   └── test-unit.rb
    └── sample
        ├── adder.rb
        ├── subtracter.rb
        ├── test_adder.rb
        ├── test_subtracter.rb
        └── test_user.rb

14 directories, 63 files
```

### CODE REVIEW

**Comment by kou** [comment]
It may be better that we have a CI job that tests against packaged files like https://github.com/ruby/csv/blob/master/.github/workflows/test.yml#L77-L94 .

**Comment by kachick** [comment]
Oh it looks useful, Thanks for letting me know! 😮 
Is it testing `test-unit` in preparing csv gem? So this PR should be reverted? 🙏

**Comment by kou** [comment]
No. It's not intended to test test-unit gem.
The test will be failed when we release a broken test-unit gem...

We should have a test for packaged test-unit.

**Comment by kou** [comment]
Ah, sorry. I might misunderstand your comment.
The CI job in csv gem doesn't use test files in test-unit gem.

**Comment by kachick** [comment]
Thank you! I misreading the ruby code ☺️

**Pull request merged**
